#!/bin/bash

##
# packdev-scripts:<PATH>
#
#   <DESCRIPTION>
#
# Author(s):
#
#   Francis (aka Anti-Physika)
#
# Copyright:
#
#   Copyright (c) 2024 Francis <antiphysika@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0
#

# Make sure $SCRIPT_NAME is set appropriately
SCRIPT_NAME="${0##*/}"

## {{{ info()
function info()
{
  echo "$@"
}
## }}}

## {{{ error()
function error()
{
  echo >&2 "$SCRIPT_NAME: error:" "$@"
}
## }}}

## {{{ die()
function die()
{
  error "$@"
  exit 1
}
## }}}

if [[ $# != 1 ]]
then
  echo "Usage: $SCRIPT_NAME <version>"
  exit 1
fi

exec git tag -s -m "Tag release: v$1" "v$1"
die "git: exec failed"

##
# vim: ts=2 sw=2 et fdm=marker :
##
